name: asalpay
description: "AsalPay."
publish_to: 'none' 

version: 1.4.2+43

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  animations: ^2.0.7
  # cupertino_icons: ^1.0.2
  flutter_otp_text_field: ^1.1.1
  fl_country_code_picker: ^0.0.4
  # pinput: ^5.0.0
  path_provider: ^2.0.15
  path: ^1.8.3
  searchfield: ^1.1.7
  liquid_swipe: ^3.1.0
  flutter_markdown: ^0.7.4+1
  fluttertoast: ^8.2.1
  lottie: ^3.1.3
  camera: ^0.11.0+2
  tflite_flutter: ^0.11.0
  carousel_slider: ^5.0.0
  bottom_sheet: ^4.0.4
  pie_chart: ^5.3.2
  # flutter_barcode_scanner: ^2.0.0
  quickalert: ^1.0.1
  rflutter_alert: ^2.0.7
  google_nav_bar: ^5.0.6
  page_view_indicators: ^2.0.0
  logger: ^2.4.0
  get: ^4.6.5
  get_storage: ^2.0.3
  progress_loader_overlay: ^4.0.1
  shimmer_pro: ^0.0.6
  provider: ^6.0.2
  responsive_framework: ^1.5.1
  shared_preferences: ^2.5.3
  font_awesome_flutter: ^10.4.0
  dropdown_search: ^6.0.1
  dropdown_button2: ^2.1.3
  image_picker: ^1.0.1
  url_launcher: ^6.0.20
  page_transition: "^2.0.9"
  intl_phone_field: ^3.2.0
  connectivity_plus: ^6.1.0
  
  pdf: ^3.10.4
  printing: ^5.11.0

  # image_gallery_saver: ^2.0.3

  gallery_saver_plus: ^3.2.8

  # gallery_saver: ^2.5.3

  google_mlkit_text_recognition: ^0.11.0
  google_mlkit_face_detection: ^0.9.0

  # google_mlkit_text_recognition: ^0.14.0
  # google_mlkit_face_detection: ^0.12.0

 

  # sms_autofill: ^2.4.1
  # pinput: ^2.2.0
  # smart_auth: ^1.1.1

  pinput: ^5.0.1 
  smart_auth: ^3.2.0

  file_picker: ^8.1.5         
  share_plus: ^11.0.0           
  open_file: ^3.5.10

  intl: ^0.18.1
  curved_navigation_bar: ^1.0.3
  logo_n_spinner: ^0.1.5
  keyboard_actions: ^4.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

# Added this, 4/6/2024 - Abdiaziz
  pointycastle: ^3.8.0 
  flutter_contacts: ^1.1.9+2
  permission_handler: ^11.3.1
  dio: ^5.7.0

  cached_network_image: ^3.0.0
  collection: ^1.15.0
  http: ^1.2.2
  flutter_dotenv: ^5.0.2
  flutter_device_type: 0.4.0
  universal_io: ^2.0.4
  app_set_id: ^1.2.0
  
  photo_view: ^0.15.0
  flutter_local_notifications: ^18.0.0
  # otp_autofill: ^4.1.0


  crypto: any
  android_intent_plus: ^5.3.0


  firebase_core: ^2.24.0

  firebase_messaging: ^14.7.10
  firebase_auth: ^4.16.0

  mobile_scanner: ^3.5.7  


  device_info_plus: ^9.1.2
  flutter_background: ^1.1.0
  iconsax: ^0.0.8
  flutter_animate: ^4.0.0
  chat_bubbles: ^1.5.0
  package_info_plus: ^8.3.0
  



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

  hive_generator: ^2.0.0  
  build_runner: ^2.4.9

  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/asalicon.png"
  min_sdk_android: 21 

flutter:

  uses-material-design: true

  assets:
    - assets/
    - .env
    - assets/aei.png
    - TermsofConAndPrivacyPl/
    - assets/OpenSans-Regular.ttf
    - assets/asalicon01.png
    - assets/mobiles.png
    - assets/tablet.png
    - assets/laptop.png
    - assets/ipad.png
    - assets/hp.png
    - assets/dell.png
    - assets/mac.png
    - assets/lenova.png
    - assets/samsung.png
    - assets/iphone.png
    - assets/tecno.png
    - assets/infinix.png
    - assets/SamsungTab.png
    - assets/ipadTab.png
    - assets/hauweiTab.png
    - assets/LenovoTab.png
    - assets/ipadAir.png
    - assets/ipadMini.png
    - assets/ipadPro.png
    - assets/ipad10.png





